export default {
	SET_LOCATION_SEARCH_TERM: "SET_LOCATION_SEARCH_TERM",
	SET_LOCATIONS: "SET_LOCATIONS",
	SET_MAP_CENTER: "SET_MAP_CENTER",
	SET_SELECTED_LOCATION: "SET_SELECTED_LOCATION",
	SET_ROUTES: "SET_ROUTES",
	SET_SELECTED_ROUTE: "SET_SELECTED_ROUTE",
	ADD_ROUTE_TO_ITINERARY: "ADD_ROUTE_TO_ITINERARY",
	REMOVE_ROUTE_FROM_ITINERARY: "REMOVE_ROUTE_FROM_ITINERARY",
	SHOW_MODAL: "SHOW_MODAL",
	REPLACE_ROUTES_IN_ITINERARY: "REPLACE_ROUTES_IN_ITINERARY",
	CLEAR_LOCATION_DATA: "CLEAR_LOCATION_DATA"
};
