export default {
  SET_LOCATION_SEARCH_TERM: "SET_LOCATION_SEARCH_TERM",
  SET_LOCATIONS: "SET_LOCATIONS",
  SET_MAP_CENTER: "SET_MAP_CENTER",
  SET_SELECTED_LOCATION: "SET_SELECTED_LOCATION",
  SET_ROUTES: "SET_ROUTES",
  SET_SELECTED_ROUTE: "SET_SELECTED_ROUTE"
};
